<?php

/**
 * @file
 * Main file of Inline Entity Form Preview module.
 */

/**
 * Implements hook_inline_entity_form_table_fields_alter().
 */
function inline_entity_form_preview_inline_entity_form_table_fields_alter(&$fields, $context) {
  // Add an entity preview column to the IEF table.
  $fields['field_ief_preview'] = array(
    'type' => 'callback',
    'render_callback' => 'inline_entity_form_preview_ief_preview_column',
    'label' => t('Preview'),
    'weight' => 101,
  );
}

/**
 * Callback for preview column.
 */
function inline_entity_form_preview_ief_preview_column($entity_type, $entity) {
  $entity->id = isset($entity->id) ? $entity->id : 0;
  return entity_view($entity_type, array($entity->id => $entity), 'inline_entity_form_preview');
}

/**
 * Implements hook_entity_info_alter().
 */
function inline_entity_form_preview_entity_info_alter(&$entity_infos) {
  foreach ($entity_infos as $bundle => $entity_info) {
    $entity_infos[$bundle]['view modes']['inline_entity_form_preview'] = array(
      'label' => t('Inline entity form preview'),
      'custom settings' => FALSE,
    );
  }
}

/**
 * Implements hook_form_field_ui_display_overview_form_alter().
 */
function inline_entity_form_preview_form_field_ui_display_overview_form_alter(&$form, &$form_state) {
  if ($form['#view_mode'] == 'inline_entity_form_preview') {
    drupal_set_message(t('This is a placeholder view mode provided by <a href="@inline-entity-form-preview">Inline Entity Form Preview</a> module. It will be used to display a preview of the entity in the %inline-entity-form widget.', array(
      '@inline-entity-form-preview' => url('https://www.drupal.org/project/inline_entity_form_preview'),
      '%inline-entity-form' => 'Inline entity form',
    )), 'status');
  }
}
